rm(list = ls())

install.packages("devtools")

install.packages("caret")
install.packages("e1071")
install.packages("rpart")
install.packages("rattle")
install.packages("glmnet")
install.packages("boot")
install.packages("xgboost")

install.packages("readr")
install.packages("purrr")
install.packages("tidyverse")
install.packages("dplyr")
install.packages("tidyr")
install.packages("reshape2")
install.packages("tidymodels")
install.packages("stringr")
install.packages("lubridate")

install.packages("RColorBrewer")
install.packages("GGally")
install.packages("ggraph")
install.packages("ggplot2")
install.packages("dbplot")
install.packages("plotly")
install.packages("rmarkdown")
install.packages("kableExtra")
install.packages("shiny")
install.packages("shinyDashboard")
install.packages("esquisse")

library(caret)
library(e1071)
library(rpart)
library(rattle)
library(glmnet)
library(boot)
library(xgboost)

library(readr)
library(purrr)
library(tidyverse)
library(dplyr)
library(tidyr)
library(reshape2)
library(tidymodels)
library(stringr)
library(lubridate)

library(RColorBrewer)
library(GGally)
library(ggraph)
library(ggplot2)
library(dbplot)
library(plotly)
library(rmarkdown)
library(kableExtra)
library(shiny)
library(shinyDashboard)
library(esquisse)
