library(AMORE)
library(RODBC)
setwd("c:/Temp")

dane <- odbcConnectExcel("WE.xls")
WE <- sqlQuery(dane, "select * from [Arkusz1$]")
WY <- sqlQuery(dane, "select * from [Arkusz2$]")
VAL_WE <- sqlQuery(dane, "select * from [Arkusz3$]")
VAL_WY <- sqlQuery(dane, "select * from [Arkusz4$]")


WE=as.matrix(WE)
WY=as.vector(WY)
VAL_WE=as.matrix(VAL_WE)
VAL_WY=as.vector(VAL_WY)
net <- newff(n.neurons=c(3,3,3,1), learning.rate.global=1e-2, momentum.global=0.5, error.criterium="TAO", Stao=NA, hidden.layer="tansig",output.layer="purelin", method="ADAPTgdwm")
result <- train(net, WE, WY,VAL_WE,VAL_WY, error.criterium="LMS", report=TRUE, show.step=100, n.shows=20 )
WYSN<-sim(result$net,VAL_WE)
wynik<- data.frame(VAL_WY,WYSN)


library(AMORE)
library(XLConnect)
setwd("d:/jarek/Jezyk_R/Interfejs_XLS")
WE<- readNamedRegionFromFile("WE1.xls", name=c("WE_UCZ","WY_UCZ","VAL_WE","VAL_WY"))
WEU=as.matrix(WE$WE_UCZ)
WYU=as.vector(WE$WY_UCZ)
VAL_WE=as.matrix(WE$VAL_WE)
VAL_WY=as.vector(WE$VAL_WY)
net <- newff(n.neurons=c(3,3,3,1), learning.rate.global=1e-2, momentum.global=0.5, error.criterium="TAO", Stao=NA, hidden.layer="tansig",output.layer="purelin", method="ADAPTgdwm")
result <- train(net, WEU, WYU,VAL_WE,VAL_WY, error.criterium="LMS", report=TRUE, show.step=100, n.shows=20 )
WYSN<-round(sim(result$net,VAL_WE),0)
WYSN<-as.data.frame(WYSN)
wynik<- data.frame(VAL_WY,WYSN)
writeWorksheetToFile("WE.xls", data=WYSN, sheet="Arkusz4",header=TRUE, startRow=1, startCol = 2)